# Generated by Django 4.2.7 on 2023-11-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('cinema_name', models.CharField(max_length=100, verbose_name='Кинотеатр')),
                ('cinema_address', models.CharField(max_length=100, verbose_name='Адресс кинотеатра')),
                ('start_work', models.TimeField(verbose_name='')),
                ('end_work', models.TimeField(verbose_name='')),
            ],
        ),
    ]
