# Generated by Django 4.2.7 on 2023-11-26 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=250, verbose_name='')),
                ('description', models.TextField(max_length=2000, verbose_name='')),
                ('duration', models.CharField(max_length=30, verbose_name='')),
                ('poster', models.ImageField(upload_to='', verbose_name='')),
                ('is_active', models.BooleanField(default=True)),
                ('release_day', models.DateField(verbose_name='')),
                ('end_day', models.DateField(verbose_name='')),
                ('genres', models.ManyToManyField(to='cinema_app.genre')),
            ],
        ),
        migrations.CreateModel(
            name='MovieSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.DateTimeField(verbose_name='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_type', models.CharField(max_length=100)),
                ('hall_name', models.CharField(max_length=255)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveIntegerField(verbose_name='Количество рядов')),
                ('seats_in_row', models.PositiveIntegerField(verbose_name='Количество мест в ряде')),
                ('is_reserved', models.BooleanField(default=False)),
                ('room', models.ManyToManyField(to='cinema_app.room')),
                ('session', models.ManyToManyField(to='cinema_app.moviesession')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.movie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.room')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.seat')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.moviesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='moviesession',
            name='cinema_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.room'),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.movie'),
        ),
    ]
