# Generated by Django 4.2.7 on 2023-11-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='end_work',
            field=models.TimeField(verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='start_work',
            field=models.TimeField(verbose_name='Начало работы'),
        ),
    ]
