# Generated by Django 4.2.7 on 2023-11-26 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='end_work',
            field=models.TimeField(default=datetime.datetime(2023, 11, 26, 20, 5, 21, 256946, tzinfo=datetime.timezone.utc), verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='start_work',
            field=models.TimeField(default=datetime.datetime(2023, 11, 26, 20, 5, 21, 256946, tzinfo=datetime.timezone.utc), verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='end_day',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 20, 5, 21, 256946, tzinfo=datetime.timezone.utc), verbose_name='День окончания проката'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_day',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 20, 5, 21, 256946, tzinfo=datetime.timezone.utc), verbose_name='День релиза'),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='show_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 20, 5, 21, 256946, tzinfo=datetime.timezone.utc), verbose_name='Время показа'),
        ),
    ]
