# Generated by Django 4.2.7 on 2023-11-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_alter_cinema_end_work_alter_cinema_start_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='end_day',
            field=models.DateField(verbose_name='День окончания проката'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_day',
            field=models.DateField(verbose_name='День релиза'),
        ),
    ]
