# Generated by Django 4.2.7 on 2023-11-26 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_alter_cinema_end_work_alter_cinema_start_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='end_work',
            field=models.TimeField(default=datetime.datetime(2023, 11, 26, 20, 6, 4, 376744, tzinfo=datetime.timezone.utc), verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='start_work',
            field=models.TimeField(default=datetime.datetime(2023, 11, 26, 20, 6, 4, 376744, tzinfo=datetime.timezone.utc), verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='end_day',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 20, 6, 4, 376744, tzinfo=datetime.timezone.utc), verbose_name='День окончания проката'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_day',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 20, 6, 4, 376744, tzinfo=datetime.timezone.utc), verbose_name='День релиза'),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='show_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 20, 6, 4, 378293, tzinfo=datetime.timezone.utc), verbose_name='Время показа'),
        ),
    ]
