# Generated by Django 4.2.7 on 2023-11-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_alter_movie_end_day_alter_movie_release_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ManyToManyField(to='cinema_app.seat'),
        ),
    ]
