# Generated by Django 4.2.7 on 2023-11-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_remove_ticket_seat_ticket_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='row',
        ),
    ]
