# Generated by Django 4.2.7 on 2023-11-26 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0005_remove_ticket_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='amount',
        ),
    ]
