# Generated by Django 4.2.7 on 2023-11-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0006_remove_ticket_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
