# Generated by Django 4.2.7 on 2023-11-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0007_ticket_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='ticket_user',
        ),
    ]
