# Generated by Django 4.2.7 on 2023-11-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0008_rename_user_ticket_ticket_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_user',
            new_name='user',
        ),
    ]
