# Generated by Django 4.2.7 on 2023-11-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0009_rename_ticket_user_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reserve',
        ),
    ]
