# Generated by Django 4.2.7 on 2023-11-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0012_purchasehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='movies_info',
            field=models.ManyToManyField(blank=True, related_name='purchase_history', to='cinema_app.ticket'),
        ),
    ]
