# Generated by Django 4.2.7 on 2023-11-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0014_remove_purchasehistory_purchase_date_ticket_buy_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='buy_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время покупки'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
